### ISSUE TITLE
How to set owl inference on fuseki with RDF-Delta

### ISSUE THREAD

**Issue by sochiseung** [afs/rdf-delta#9]
I'd configured and used a fuseki like below; 

fuseki dataset.ttl
```
@prefix :      <http://base/#> .
@prefix tdb:   <http://jena.hpl.hp.com/2008/tdb#> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix ja:    <http://jena.hpl.hp.com/2005/11/Assembler#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix fuseki: <http://jena.apache.org/fuseki#> .

:service_tdb_all  a                   fuseki:Service ;
        rdfs:label                    "TDB ds" ;
        fuseki:dataset                :dataset ;
        fuseki:name                   "ds" ;
        fuseki:serviceQuery           "query" , "sparql" ;
        fuseki:serviceReadGraphStore  "get" ;
        fuseki:serviceReadWriteGraphStore
                "data" ;
        fuseki:serviceUpdate          "update" ;
        fuseki:serviceUpload          "upload" .

:dataset a ja:RDFDataset ;
    ja:defaultGraph       <#model_inf> ;
    ja:namedGraph
       [ ja:graphName      <https://www.kebhana.com/ontology/no_inf> ;
         ja:graph          <#graph> ] ;
     .

<#model_inf> a ja:InfModel ;
     ja:baseModel <#graph> ;
     ja:reasoner [
         ja:reasonerURL <http://jena.hpl.hp.com/2003/OWLFBRuleReasoner>
     ] .

<#graph> rdf:type tdb:GraphTDB ;
  tdb:dataset :tdb_dataset_readwrite .

:tdb_dataset_readwrite
        a             tdb:DatasetTDB ;
        tdb:location  "/fuseki/databases/ds" .
```

And I want to apply this configuration code on the fuseki which connected with rdf-delta.
Specifically, I would like to use the inference and synchronization functions, how do I modify the configuraion file?

Thank you.

**Comment by afs** [comment]
@sochiseung,

Good question! The issue I see is that reasoners cache some things so directly changing the base data does not change the reasoner.

If it was only backwards rules on the data, then changing `:tdb_dataset_readwrite` to be `delta:DeltaDataset` (examples: https://github.com/afs/rdf-delta/tree/master/rdf-delta-examples/ExampleFusekiConfigs) may work.

A better way would be if the assembler for `delta:DeltaDataset` were extend so that instead of `delta:storage` being a set of options for internally managed datasets, it allowed a full description, which would be `:dataset`. This is the "external" option for setting a Delta dataset up which exposes the internal mechanism for doing (`delta:storage "external"` is legal syntax) but not implemented.

Other than that, it needs java I'm afraid to say.

**Comment by afs** [comment]
FYI
I've just pushed initial code to address this use case. A DeltaDataset  can say, instead of `delta:storage`, it can say `delta:dataset` (it is really "storage=external" + definition of "external").

    ...
        fuseki:dataset                :deltaDataset ;
    ...
    :deltaDataset rdf:type delta:DeltaDataset ;
        delta:changes  "http://localhost:1066/" ;
        delta:patchlog "ABC";
        delta:zone "Zone";
        delta:dataset :dataset ;
        .
    
    :dataset a ja:RDFDataset ;
    ...

**Comment by afs** [comment]
The 0.8.0 RDF Delta release has this support for datasets described in the Fuseki configuration file.
